### ISSUE TITLE
"Unser Studio" wird nach Logout nicht neu geladen

### ISSUE THREAD

**Issue by dennis-** [hcrudolph/swe-project#102]
Nach dem Ausloggen wird die Default-Page nicht geladen, man kann auch auf der Seite navigieren, auf der man zuletzt war. (siehe Screenshot)
![issue](https://cloud.githubusercontent.com/assets/7447722/5703311/500664c8-9a65-11e4-8338-82a5f036477c.png)

**Comment by rodichsv** [comment]
Der normale Redirect im AppController scheint nicht zu greifen.
Ich vermute, dass hier was angepasst werden muss: (AccountsController)
                if ($this->Auth->logout()) {
                    $view = new View($this, false);
                    $answer['logout'] = true;
                    $answer['message'] = 'Sie wurden erfolgreich ausgeloggt';
                    $answer['login'] = $view->element('authentification/login');
                    $answer['sidebar'] = $view->element('sidebar');
                } else

und dann View->Elements->logout.ctp

            if(json.logout == true)
            {
                notificateUser(json.message, 'success');
                $('#sidebar').replaceWith(json.sidebar);
                $('#authentification').html(json.login);
            }

---
Wer hat das damals gemacht ?

**Comment by bortim** [comment]
Bei diesem Ticket müssen wir an zwei Stellen schrauben.

- [ ] Deny der Controlleraktionen @rodichsv

- [ ] Ausführen des JavaScripts in der Sidebar zum Laden des aktiven Eintrags

**Comment by rodichsv** [comment]
Super Markus, vielen Dank!
Für mich scheint das jetzt problemlos zu funktionieren. Welche Conrolleraktionen sollen denied werden?

**Comment by bortim** [comment]
Ich würde fast behaupten, dass es alle von Aktionen von TariffsController, CertifikatesController und RoomsController betrifft.

**Comment by hcrudolph** [comment]
Kann den Fehler aktuell nicht mehr nachbilden.
Die Denyregeln sind doch sowieso drin, wenn der User nicht eingeloggt ist.

**Comment by bortim** [comment]
Hallo Hans,
du hast recht, da fehlt nichts mehr.
Es betrifft aber noch den UsersController mit der Action 'listing' (wenn nicht sogar alle Aktionen).

**Comment by rodichsv** [comment]
Hi Markus,
der Userscontroller ist meines Erachtens an den Accounts-Controller gebunden (account.role), dieser hat bereits den beforefilter, dass nur login/checklogin geht. Ohne eingeloggt zu sein, können so keine Listing o.ä. Funktionen im Userscontroller abgerufen werden.
Und bei listing & allen anderen Funktionen wird auf die Rolle geprüft.

**Comment by bortim** [comment]
Vom usersController existiert eine Verbindung zu Account (und Person).
Zum AccountsController nicht.
Deswegen muss die login-Berechtigung im UsersController extra gemacht werden.

**Comment by rodichsv** [comment]
Der BeforeFilter() begrenzt auf login/checklogin und die Funktionen sollten analog zum AccountsController sein.

**Comment by bortim** [comment]
Hallo Sven,


ich glaube, dass wir etwas aneinander vorbeireden.


Account->Login - ohne Login

Account->checklogin - ohne Login

Users->listing (und alle Aktionen) - mit Login


Wenn das nun so ist, dann schließ das Ticket

**Comment by bortim** [comment]
da8b5d2ada3433250aa4ae347aaff00f134f3d36
f0b70d5dd4e599b25a0ac69090d5c766b23e88a0
