### ISSUE TITLE
Neuen Kurs anlegen - Internal Server Error

### ISSUE THREAD

**Issue by brauna01** [hcrudolph/swe-project#106]
Database Error

Error: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Tariff.course_id' in 'where clause'

SQL Query: SELECT `Tariff`.`id`, `Tariff`.`amount`, `Tariff`.`description` FROM `fitness`.`tariffs` AS `Tariff` WHERE NOT (`Tariff`.`course_id` IS NULL)

Notice: If you want to customize this error message, create app/View/Errors/pdo_error.ctp

?? @hcrudolph

**Comment by bortim** [comment]
Ich behaupte mal, dass es an der Bedingung liegt, wo die tarife zusammengesucht werden.
Also bei add und edit.

**Comment by hcrudolph** [comment]
`Tariff.course_id` gibts nicht mehr.
Wo fragt er das denn noch ab?

**Comment by bortim** [comment]
Kurse können wieder angelegt werden.
Dementsprechend Close.
