### ISSUE TITLE
Zu langeTrainer-Emailadressen

### ISSUE THREAD

**Issue by hcrudolph** [hcrudolph/swe-project#108]
Bei den Trainern sehen lange Email-Adressen noch etwas unschön aus:

![Overflow](http://i.imgur.com/ScdEQvh.png)

**Comment by tkoberom** [comment]
Habe ich schon an Alex weitergegeben. Er hat dies schon behoben, allerdings möchte er erst pushen nachdem Johannes die Änderungen am Popover gepusht hat.

**Comment by bortim** [comment]
Pushen. Am Ende gibt es nur wieder merge-Probleme.

**Comment by brauna01** [comment]
![mail-lange](https://cloud.githubusercontent.com/assets/8896573/5789767/c23ac6bc-9e78-11e4-9346-1a696b44aa06.jpg)
52d5a741ff6482128b5fac3021415b95cd1731c7 behebt das Problem bei allen aktuell verwendeten Mail-Adressen. Wenn die noch länger werden, müsste man sich noch was anderes einfallen lassen :O
