### ISSUE TITLE
[Controller] Keine Einschränkungen bezüglich des Logins

### ISSUE THREAD

**Issue by bortim** [hcrudolph/swe-project#14]
Derzeit kann, wenn man die Links bzw Requests per AJAX sendet, alle Aktionen machen.
Hier müsste man Konzepte für die einzelnen CRUD-Funktionen überlegen.

Eine Unterscheidung aus direktem HTML und JSON wäre wohl ganz gut.

**Comment by rodichsv** [comment]
Ich denke das Thema ist erledigt.
