### ISSUE TITLE
[Controller] Hervorhebung falscher Eingaben

### ISSUE THREAD

**Issue by bortim** [hcrudolph/swe-project#21]
Bei allen Input-Feldern muss bei fehlerhaften Eingaben das betroffene Feld hervorgehoben werden.
Eine Hinweisnachricht wäre wünschenswert.
- [X] Fehlermeldungen bei der Kursplanung (Vorlage erstellen) [8d1960cb9e151970a737aff9ea68b39150df372b]

**Comment by JannikZed** [comment]
Hier fehlt derzeit noch bei der Kursplanung eine Exception. Geht man auf den Terminplaner und vergisst ein Feld, so wird dieses nicht hervorgehoben sondern das Erstellen einer Vorlage funktioniert einfach nicht. -> So hebet es hervor ihr Programmierer

**Comment by bortim** [comment]
Da bisher keine Einwände des Tests waren: Close
