### ISSUE TITLE
[Account+Person] Herausfiltern nichtänderbarer Attribute

### ISSUE THREAD

**Issue by bortim** [hcrudolph/swe-project#28]
Wenn ein Nutzer die falsche Rolle hat, so soll er seine Anschrift, etc nicht ändern können.
Dies müsste man vor dem Speichern prüfen und ggf. 'unset'ten.
```php
if(isset($this->data[$this->alias]['attribut']) AND $user['role'] == 0) {
unset($this->data[$this->alias]['attribut']);
}
```

**Comment by rodichsv** [comment]
Ich denke, das Thema ist dann auch vom Tisch.

**Comment by bortim** [comment]
Da bin ich mir noch nicht so sicher.
Man kann nämlich die requests auch faken. Damit könnte man die Daten trotzdem an den Controller senden (und abändern). Ich weiß aber nicht, inwiefern du dem im Controller schon entgegengewirkt hast.

**Comment by rodichsv** [comment]
Dagegen sind wir meines Erachtens nicht besonders geschützt. Es sind lediglich im Allgemeinen die CRUD Funktionen nach Rollen eingeschränkt. Bei Edit() lasse ich die Rolle unsetten bei Role 1. 
Aber wird unsere Professorin solche Funktionen wirklich testen und Anfragen an den Server absichtlich faken ? :)

**Comment by bortim** [comment]
Diese Sicherheit wollte ich ja eben durch dieses Issue herstellen.
Ob sie das macht oder nicht, kann ich nicht beurteilen.
Ich kann nur sagen, dass da unsere Anwendung eine schwachstelle hat.=

**Comment by rodichsv** [comment]
Ich öffne das Issue wieder und bitte um Meinungen/Vorschläge zu dem Thema.:)

**Comment by bortim** [comment]
Meine Vorschläge hast du ja.
Wir müssten Elemente rausfiltern (unsetten), die man bei falscher Rolle nicht andern darf.
Z.b. Anschrift, etc.=

**Comment by rodichsv** [comment]
Hi Markus,
hab es gerade erledigt ;)
Wir sind im Backend jetzt sicher.
Rolle = 0 darf nur Username, Password und E-Mail ändern von sich selbst ändern (Andere User werden bereits durch listing gefiltert.)
Rolle = 1 kann User mit Rolle = 2 nicht bearbeiten (bzw. kann er sie bearbeiten aber nicht speichern)
Rolle = 2 darf weiterhin alles

**Comment by bortim** [comment]
Super!=

**Comment by rodichsv** [comment]
Felder sind im Frontend jetzt auch disabled wenn Role = 1 -> Role = 2 bearbeiten will. Macht das ganze etwas auch etwas übersichtlicher.

**Comment by bortim** [comment]
@rodichsv 
Gibt es noch offene Punkte, die du bezüglich diesem Problem behandeln willst?
Wenn nein, dann close. :+1:

**Comment by bortim** [comment]
:+1:
