### ISSUE TITLE
Account-Verwaltung - Rollenanpassung

### ISSUE THREAD

**Issue by brauna01** [hcrudolph/swe-project#32]
Habe gemerkt, dass ich als Mitarbeiter/Mitglied angemeldet war, aber ohne weiteres meinen eigenen Status auf Administrator ändern konnte!?
Zurück ändern geht nicht, da man selbst als Administrator nicht die Rechte hat, Administratoren die Rechte zu entziehen (weder anderen noch einem selbst).

**Comment by rodichsv** [comment]
done
