### ISSUE TITLE
[PostsController] Fehlende Page-Anzeige

### ISSUE THREAD

**Issue by bortim** [hcrudolph/swe-project#38]
Auf der index-Seite wird bei < $Limit keine Seite angezeigt.
Sollte aber 1 sein

**Comment by bortim** [comment]
Ebenso ist die Anzeige der Seitenzahl fehlerhaft.

**Comment by bortim** [comment]
@StephanWagener 
Der leichteste Weg wäre, wenn du die Anzahl der gelieferten postings gegen 0 prüfst.
Wenn es null ist, dann machst du selbst einen Eintrag (Es sind keine Einträge vorhanden, etc.)

**Comment by brauna01** [comment]
weiß ich jetzt leider nicht genau was du meinst

**Comment by bortim** [comment]
Wenn keine posts vorhanden sind, so ist die Seitenanzeige nicht existent. Eine Anzeige, dass nichts existiert gibt es auch nicht.

**Comment by bortim** [comment]
Ich finde die Meldung irgendwie unpassend.
Sticht ziemlich aus dem System heraus.

**Comment by StephanWagener** [comment]
Meldung wurde angepasst! Falls das jetzt so passt kann dieser Issue geschlossen werden.

**Comment by bortim** [comment]
Jo. Ich denke das kann man so lassen.

Fügt sich zwar immer noch nicht wirklich gut in die Seite, aber okay.

Ist nicht so tragisch.

**Comment by StephanWagener** [comment]
Gut dann ist das hiermit geschlossen, weil der Oberguru das okay gegeben hat. :D
