### ISSUE TITLE
[View] Full clickable Collapse

### ISSUE THREAD

**Issue by bortim** [hcrudolph/swe-project#40]
Die Collaps-Panels sind derzeit nur per Klick auf die Überschrift ausklappbar.
Besser wäre es, wenn der ganze Header zum ausklappen funktionieren würde.
Beispiel: Kursliste im Kursmanagement

**Comment by brauna01** [comment]
wegen zu großem Aufwand erstmal auf Eis gelegt - abgesprochen mir Markus - closed
