### ISSUE TITLE
[ListsController] Tarifliste

### ISSUE THREAD

**Issue by bortim** [hcrudolph/swe-project#52]
Eine Tarifliste würde den Interessenten nicht schaden.

**Comment by hcrudolph** [comment]
Da wir jetzt *einen* Tarif als Grundbetrag implementiert haben, ist das hinfällig. Nur diesen Betrag müsste man irgendwo zugänglich machen. Genauere Unterscheidungen sind - zumindest für die Mitglieder - nicht gefordert. In der Rechnung wird der monatliche Betrag für Mitglieder und Admins über die Rolle bestimmt. (Admin hat Festbetrag, weil er nicht unbedingt Dates hat) Lediglich die Mitarbeiter/Trainer werden stundenweise bezahlt.

**Comment by rodichsv** [comment]
Das könnte man ja groß oben im Slider als dauerhafte Information propagieren ?

**Comment by bortim** [comment]
Ansonsten hätten wir noch unter dem Login etwas Platz.

**Comment by hcrudolph** [comment]
Wir waren uns doch einig, dass wir den Punkt "Listen" irgendwie umbennenen wollen.. bzw. "Unser Studio". Da würde das wohl am ehesten hinpassen.

**Comment by jmpy-** [comment]
Umbenannt

**Comment by bortim** [comment]
Die Kurszeiten habe ich hart ins Template geschreiben.
Auch an anderen stellen steht einfach hart der Text drinen.
Deswegen: Auch hier den Text hart reinschreiben. Übernimmst du das, Johannes?
Da die Posts alle wichtigen Informationen für den Nutzer beinhalten, würde ich das lassen. (auch wegen Arbeitsaufwand).

**Comment by jmpy-** [comment]
Ok, Studioinfo page ist bei mir im to-do

**Comment by bortim** [comment]
Aufgrund der Festlegung, dass es lediglich einen Preis für alle Mitglieder gibt, werden Preise statisch in die Seite geschrieben [d7e0aebf1ab1b179ec9fb645efaf1a7b62123181].
