### ISSUE TITLE
[Controller] Abmanagen unnötiger Aktionen

### ISSUE THREAD

**Issue by bortim** [hcrudolph/swe-project#55]
- [X] [DatesController] index, view [848e0a8dc13d2756a2ab2bb35ca90485837cf2dc]
- [X] [AccountsController] CRUD-Methoden [5e2ab9832818472299e2842239f4d0b6718e9766, a8ccf61ea9f90736eb7072ff0c521d3a9c117204]
- [X] [StudioController] Rechnungsdaten, Abrechnungsdaten
- [X] [PeopleController] Alle Aktionen nicht in Verwendung [47415c5fd86050a16df305c6f008801b23cc7d2b]
- [X] [AccountsController] Abmanagen von ACL [8f06e9dff2d4d925b8c2fa89b51e28d6a8a7d5f2]
- [X] [StudioController] Abmanagen der Kursansicht @StephanWagener [66d44a7a5a6c3d81026913138ba028e458a6aa12]
- [X] [UsersController] Abmanagen der Trainingspläne [d73de0031158be8dbe0d9b374e292def3af235f6]
- [X] [UsersController] Abmanagen der Tabs [d73de0031158be8dbe0d9b374e292def3af235f6]

**Comment by bortim** [comment]
Da die Abrechnungsdaten und Rechnungsdaten durch einen Cronjob ausgelöst werden, werden diese nicht mehr benötigt.

**Comment by bortim** [comment]
@rodichsv Kannst du dich zu den Permissions rund um ACL äußern?
Werden die noch benötigt, oder können diese abgemanaged werden?

**Comment by rodichsv** [comment]
Wird nicht gebraucht, haben wir über Fieldsets und direkten Role-Abfragen gelöst, außerdem war die ACL für unsere Anforderungen zu unflexibel. Hab es rausgenommen.

**Comment by bortim** [comment]
Da die Kursplanung 100% mit der vom Studiomanagement-Tab übereinstimmt, können wir diesen Abmanagen.
@StephanWagener: Bitte erledigen

**Comment by bortim** [comment]
Aufgrund des einheitlichen Basistarifs benötigen wir keine Tarifansicht mehr.
@StephanWagener: Bitte abmanagen

**Comment by bortim** [comment]
Trainingspläne und Zertifikate und dadurch der ganze tab werden nicht mehr benötigt.
du kannst im Studiomanagement die Tasks von Stephan übernehmen?
@tkoberom: Bitte Abmanagen

**Comment by brauna01** [comment]
ist mit "[StudioController] Abmanagen der Kursansicht" der Teil hier gemeint?
![kursansicht](https://cloud.githubusercontent.com/assets/8896573/5672473/df8c0544-9790-11e4-95ac-a740d9ee96b0.jpg)
finde das sollte man lassen, da es eine schöne Übersicht ist. Wenn was anderes gemeint ist, bitte aufklären :)

**Comment by bortim** [comment]
Du bist im listscontroller. Hier geht es um den studiocontroller.

**Comment by brauna01** [comment]
Das müssten zumindest mal die letzten beiden Punkte sein?! b6fd98ecae07494f39b5ada632e539bda3a6f35f

**Comment by bortim** [comment]
Du müsstest die ganze Aktion löschen.
Users/index.ctp
Danach in dem Controller rausbauen.
In der Sidebar den Link $this->webroot; ?>Users/listing/<?php echo $user['id'];

**Comment by bortim** [comment]
Hab ich übernommen: d73de0031158be8dbe0d9b374e292def3af235f6

**Comment by bortim** [comment]
Kann sich jetzt noch bitte jemand dem ausbau des Kurstabs widmen...
@StephanWagener @brauna01 @tkoberom

**Comment by tkoberom** [comment]
Wenn keine Einträge in News vorhanden sind, wird eine entsprechende Meldung wiedergegeben. Allerdings steht diese Meldung immernoch da, wenn man einen Eintrag hinzufügt und wenn man zu einem anderen Tab wechselt und wieder zurück ist die Meldung wieder weg. 
Kann mir jemand sagen wie ich die Seite refreshe?

**Comment by bortim** [comment]
Was hat das mit diesem Issue zu tun?

**Comment by bortim** [comment]
Da Stephan den letzten, offenen Punkt beendet hat: Close

**Comment by tkoberom** [comment]
Ohh stimmt. Ich hab das von Stephan übernommen und ich dachte, dass es sich auf diese Issue bezieht. Ich erstelle eine neue Question.
