### ISSUE TITLE
ListsController liefert keine Personendaten bei Trainer

### ISSUE THREAD

**Issue by jmpy-** [hcrudolph/swe-project#56]
In der Trainerview sollen Name und weitere Infos > Zertifikate der Trainer angezeigt werden, diese Infos werden vom ListsController in function trainer() derzeit nicht bereitgestellt.

**Comment by jmpy-** [comment]
Leider liefert trainer() immer noch keine Zertifikate, für diese gibt er ein leeres array [Certificate] zurück obwohl z.B. Borti schon Zertifikate zugeordnet sind

**Comment by bortim** [comment]
Du kannst es derweil mit Fehler implementieren.
Description wird aber nie gefüllt werden.

**Comment by bortim** [comment]
Der Fehler liegt darin: Ein Trainer (Mitarbeiter) kann ja mehrere Zertifikate haben.
Dementsprechend ist $result['Cartificate'] ein weiteres Array.
```php
foreach($result['Cartificate'] as $certificate)
{
    echo $certificate['name'];
}
```

**Comment by bortim** [comment]
Fehler bezüglich der fehlenden Zertifikate wurde mit 7f7218a9eaba9b4eb66a14f10b528779eac39cf2 behoben.

**Comment by jmpy-** [comment]
ich mache hier mal zu, falls wegen Performance noch was daran gedreht werden muss, bitte nochmal assignen
