### ISSUE TITLE
[CalendarController] Aktion bei Klick auf Kalendereintrag

### ISSUE THREAD

**Issue by bortim** [hcrudolph/swe-project#59]
Welche Seite soll durch einen Klick geladen werden?
Ich würde den darüberliegenden Kurs aufrufen und als modalen Dialoganzeigen.
Diese Funktion wäre für den Kurs bereits implementiert.
Man müsste lediglich die Funktion von der Indexsseite in die application.js verlagern.

Als 'link' müsste man dann eben "javascript:funktion(Parameter)" ausgeben.

**Comment by hcrudolph** [comment]
Ist das Date an der Stelle vielleicht aussagekräftiger?
So sieht man gleich, ob für diesen Termin noch Plätze frei sind.

**Comment by hcrudolph** [comment]
Nevermind, da der Kalender auch für Nicht-Mitglieder zugänglich ist, sollte der Course angezeigt werden. Geht in Ordnung :+1:

**Comment by bortim** [comment]
Wie sieht es mit Prio aus?
Ist ja jetzt nicht soo wichtig, macht aber trotzdem etwas (viel) Arbeit.

**Comment by hcrudolph** [comment]
Nope, sicherlich nicht. Das ist sowas für KW. 2-4 (wenn überhaupt).

**Comment by bortim** [comment]
Die Klick-Funktionalität wurde entfernt.
