### ISSUE TITLE
Email-Versand

### ISSUE THREAD

**Issue by bortim** [hcrudolph/swe-project#61]
- [X] Absagen (Kurs abgesagt)
- [x] Zusagen (Kurs angemeldet, Kurs abgemeldet)
- [x] Informationen (Postsystem)
- [x] Abrechnungen @hcrudolph 
- [x] Erinnerungen @hcrudolph -> Welche Erinnerungen?

**Comment by hcrudolph** [comment]
- [ ] Abrechnungen 
... werde ich versuchen mit der BilanzShell zu koppeln. Wird die XML-Daten versandt, wird auch der User informiert (evtl. mit den von ihm belegten Kursen)
- [ ] Erinnerungen 
... 24h vor Kursbeginn eine E-mail an die Teilnehmer. Das scheint mir am sinnvollsten.
- [ ] Informationen und Erinnerungen
... :worried:

Was meinst du @rodichsv?

**Comment by bortim** [comment]
Okay. Die Erinnerung würde ich als weiteren Cronjob gestalten, der um 00:00 anläuft.
Kannst du das übernehmen, @hcrudolph 
Für Informationen haben wir ja das Post-System. Dies kann man ja auch als elektronisch durchgehen lassen.

**Comment by bortim** [comment]
@hcrudolph 
Wie sieht es bei dir mit Erinnerungen und den Abrechnungsinformationen aus?

**Comment by bortim** [comment]
336c8cda7a81ff262a854d81c26cef7324026199
24a2cbcc0e94c666bf07f9b81609337cf7699103
99f4c98a6d488c13f1d8983ea19d2f8d077ed9da
