### ISSUE TITLE
[DatesController] Verhalten Min-Teilnehmer nicht erreicht

### ISSUE THREAD

**Issue by bortim** [hcrudolph/swe-project#62]
Wir haben derzeit kein Verhalten präzisiert, wie und wann geprüft wird, ob ein Termin die Min-Teilnehmer erreicht hat und dementsprechend stattfindet.

**Comment by rodichsv** [comment]
Ich würde sagen wenn Teilnehmer zwischen min() und max() dann passiert gar nichts. Sollte zum Zeitpunkt x nicht genügend zusammenkommen den Termin absagen. Bei max() keine Anmeldung mehr möglich.

Allerdings mal salopp gesprochen, findet nicht in jedem Fall immer der Kurs statt? Im Fitnessstudio gibt es den Kurs immer ohne Mindestanzahl, die Trainer führen den zur Not auch nur mit 1 Mitglied durch, deswegen sollten wir uns fragen nicht die Min-Abfrage wegzulassen?

**Comment by bortim** [comment]
Mein Hintergrund ist eher der: Wir fragen (bisher) zu keinem Zeitpinkt ab, ob der Termin ausfällt.
Es ist auch nicht explizit in er Aufgabenbeschreibung.
Deswegen würde ich sagen: drinnen lassen, da wir es schon überall berücksichtigt haben, aber nicht abprüfen und dadurch eine Absage veranlassen.
Das können dann unsere Nachfolger machen.
