### ISSUE TITLE
Nutzer hinzufügen (Schönheitsfehler)

### ISSUE THREAD

**Issue by Us3r12345** [hcrudolph/swe-project#63]
Usermanagement > Hinzufügen
(Windows 8.1, Firefox 34.0)

![fehler](https://cloud.githubusercontent.com/assets/9152565/5602616/9f40342c-935a-11e4-8dee-91e45bc970d8.jpg)

**Comment by Us3r12345** [comment]
Auch bei der Eingabe von Inhalten sind diese für mich genau so wenig sichtbar. Das ist natürlich für den Nutzer sehr ungünstig.

**Comment by brauna01** [comment]
Bin ich im Moment  dran

**Comment by bortim** [comment]
Das Problem liegt an der panel-body-Klasse. Diese definiert einen padding-Wert. In Chrome (womit wohl die meisten arbeiten, da das noch niemanden aufgefallen ist), tritt dieses Fehlverhalten nicht auf.
Aufgrund der Abhängigkeiten des paddings im panel-Body auf der Postsseite und ggf. anderen Javascripten, ist es wohl der einfachste Weg die Elemente mit padding:0px; zu versehen.
```css
.panel-body-input {
    padding:0px;
}
```
Diese Klasse müsste dann wohl bei so ziemlich allen Input-Feldern, die gleichzeitig der Body eines Panels sind, angegeben werden.

**Comment by brauna01** [comment]
Jetzt ist wirklich closed.
