### ISSUE TITLE
Unser Studio - unfertiges Popover

### ISSUE THREAD

**Issue by JannikZed** [hcrudolph/swe-project#64]
Auf der Seite "unser Studio" unter "Trainer" werde diese dargestellt, als ob man sie anklicken kann. Ebenfalls wird bei Trainer Markus ein Popover angezeigt. Beides bringt nichts und sollte an die Darstellung unter Mitarbeiter angepasst werden.
![bildschirmfoto 2015-01-03 um 16 29 02](https://cloud.githubusercontent.com/assets/7526174/5602796/b4782254-9365-11e4-8836-5e906308e698.png)

**Comment by jmpy-** [comment]
in Arbeit, da kommt Trainerinfo hin...

**Comment by jmpy-** [comment]
Ist jetzt bis auf DB-Abfrage schonmal funktionstüchtig mit korrektem Popover verhalten

**Comment by bortim** [comment]
@jmpy- um welche db-Abfrage geht es konkret?

**Comment by JannikZed** [comment]
Positionierung und alles passt, schaut gut aus. Ich möchte noch paar andere Zertifikate anlegen und zuweisen und schauen, ob das alles funzt, dann schließ ich hier
