### ISSUE TITLE
Checkbox selbst nicht klickbar (Studiomanagement -> (Ab)Rechnungsdaten)

### ISSUE THREAD

**Issue by brauna01** [hcrudolph/swe-project#65]
Beim Studiomanagement --> Rechnungsdaten & Abrechnungsdaten werden die Checkboxen nur (un)checked, wenn man auf den Text daneben (aktuell "User X") klickt. Ein Klick auf die Box selbst ändert nichts.

**Comment by bortim** [comment]
References #55
Die Abrechnungsdaten und Rechnungsdaten werden per Skript ausgeliefert.
Die Funktionalität wird, wie im verlinkten Issue abgebaut
