### ISSUE TITLE
Schlechte Performance in der Lösung für alternatives Userbild

### ISSUE THREAD

**Issue by jmpy-** [hcrudolph/swe-project#66]
Derzeit sieht man z.B. in UnserStudio -> Mitarbeiter, wie sich zunächst die Userbilder laden und dann Stück für Stück durch die onError Funktion das Default Bild eingesetzt wird.

Bin da mittlerweile überfragt, eine jscript Lösung habe ich nicht implementiert bekommen, dazu bin ich wohl zu blöd.

**Comment by brauna01** [comment]
Evtl Background-Img und falls Bilder vorhanden, diese drüber laden. Skype?

**Comment by bortim** [comment]
Leider hat mein Push das Problem nicht gelöst.
Dieses liegt eigentlich auf Seiten des Servers, da er über 1.5 Sekunden zum laden benötigt hat.
Als möglichen Lösungsweg würde ich folgendes vorschlagen:
1. img: src=Default-Bild
2. img: src=user-Bild.
Auf zweites Bild legen wir einen handler: load -> lösche img1, error: lösche img 2

**Comment by bortim** [comment]
Das Problem wurde gelöst.
c0c4f6231f30c9e57b76e94f3b8ad37f32254174
8c6c5e3795ee79796806a8574bc44398a6eb716a
8251791767ff867fede38077ec3546ce8e9120c7
af39430a807a211670c81b49ebcc5da1fcc559e2
