### ISSUE TITLE
[View] Klassen- statt Id-Formattierung

### ISSUE THREAD

**Issue by bortim** [hcrudolph/swe-project#67]
Anstatt jeden Button per Id zu positionieren eine Klasse dafür erstellen und jedem Button zuordnen

**Comment by brauna01** [comment]
Hinzufügenbuttons alle über die btn-default Klasse angesprochen

**Comment by tkoberom** [comment]
Wurde umgesetzt.

**Comment by bortim** [comment]
Im Kursmanagement hat sich noch eine falsche ID (userAddOpenButton) versteckt.
Ich denke, dass sie beim User selbst auch nicht mehr gebraucht wird.
Bitte entfernen
