### ISSUE TITLE
[View][Modale Dialoge] Verzogene buttons im Footer

### ISSUE THREAD

**Issue by jmpy-** [hcrudolph/swe-project#69]
Die beiden unteren Buttons 'schließen' und 'Kursdaten speichern' haben unterschiedliche Anzeigehöhe

![capturfiles_1](https://cloud.githubusercontent.com/assets/6022262/5606087/1029b33a-941d-11e4-8333-295134e4f801.png)

**Comment by bortim** [comment]
Das Problem tritt komischerweise in allen modalen Dialogen auf.
Der einfachste weg wäre um die beiden Buttons jeweils eine Button-Group zu legen.
sie sehen zwar dann etwas anders aus, fügt sich aber ganz gut in das restliche Design ein.
Wichtig ist, dass die die Tags der Buttons an sich nicht verändert werden.
Am einfachsten lediglich den div-container kopieren.
```html
<div class="btn-group">
    <button type="button" class="btn btn-default" data-dismiss="modal">Button1</button>
  </div>
```
Zusätzlich würde ich eine Liste erstellen, wo dieser Fehler überall auftritt.

**Comment by bortim** [comment]
Bitte dementsprechend bearbeiten und hier abhaken
- [ ] Kurs erstellen
- [ ] Kurs bearbeiten
- [ ] Termin erstellen
- [ ] Termin bearbeiten
- [ ] User bearbeiten
- [ ] User erstellen

**Comment by tkoberom** [comment]
Problem wurde behoben ...Alle Buttons beziehen sich auf diese Klasse ".modal-footer .btn+.btn{margin-bottom:10px;margin-left:5px}."
Dort habe ich das Margin-Button von 0 auf 10 gesetzt, was dem default-Button entspricht.

**Comment by bortim** [comment]
Bei mir hat sich leider nichts geändert.
Ebenso gefällt mir die Änderung im bootstrap-file nicht.
Für Applikations-Sachen haben wir extra die application.css
Da dein Fix aber nicht greift bitte den oberen, sauberen Weg umsetzen.

**Comment by bortim** [comment]
@tkoberom :+1: 
Scheinbar gab's am Server wieder 'n Problem.
Die Änderung funktioniert.
Nichtsdestotrotz: Bitte mach keine Änderungen an der bootstrap.css
Wenn dir die Button-group besser gefallen sollte, dann kannst du diese gerne noch implementieren.
Ist eben etwas mehr Aufwand. Ansonsten: close the issue

**Comment by tkoberom** [comment]
Bei mir hat der Fix schon gegriffen. 
Wenn ich die application.css verwenden will, muss ich das Margin (was vor meinem Fix auf "0" gesetzt war) komplett aus der Bootstrap-Klasse herrausnehmen. D.h. man muss sowieso die Bootstrap ändern.

**Comment by bortim** [comment]
Okay.. Mit der btn-group hätten wir das Problem nicht, das Design hätte sich aber geändert.
Dann machen wir das jetzt dicht, da es funktioniert.
