### ISSUE TITLE
[Usermgmt]fertigzustellende Tabs

### ISSUE THREAD

**Issue by jmpy-** [hcrudolph/swe-project#70]
Tabs Trainingspläne und Zertifikate fehlen noch großteils

**Comment by bortim** [comment]
Zertifikate werden nicht dauernd umgeändert und sind derzeit nur bei Trainer wichtig.
Mein Vorschlag: Das muss man händisch in der Datenbank drehen.
Laut Anforderung müssen nur die User vom System gemanaged werden.
Trainingspläne sind meines Wissens nach auch nicht in der Aufgabenbeschreibung gefordert.
Eine Implementierung würde ich deswegen ersteinmal außen vor lassen.
@hcrudolph: Segnest du das ab?

**Comment by hcrudolph** [comment]
Exakt. Beides erstmal nicht Prio.

**Comment by bortim** [comment]
Ich schließe, da wir das im rahmen dieses Projekts nicht mehr umsetzen werden.
