### ISSUE TITLE
Medien für Header, Studio, Mitarbeiter etc.

### ISSUE THREAD

**Issue by jmpy-** [hcrudolph/swe-project#72]
Wer kann sich denn um Lizenzgerechte Stockphotos für Header, für die Mitarbeiter, für das Studio etc. kümmern?
Oder sollen wir das alles mit eigenen Bildern füllen. Ist dann jeder mit der Verwendung einverstanden, oder machen wir es wie Hans und malen alle Portraits etc.

**Comment by bortim** [comment]
Es gibt seiten, wo urheberrechtsfreie Bilder angeboten werden..
Da gibt es sicherlich auch hierfür bilder.
wenn es lediglich um das img geht, dann hätte ich noch eine Möglichkeit:
```html
<span class="glyphicon glyphicon-user" style="font-size: 10em;" aria-hidden="true"></span>
```
Muss man dementsprechend aber an das System anpassen.

**Comment by JannikZed** [comment]
Ich hab ja schon ein paar rausgesucht und werde noch weitere finden, damit das ganze bei Mitarbeiter und Trainer seriös aussieht. Alle Bilder sind lizenzfrei. @jmpy- du baust das dann schön ein bei Kurse und evtl header? :)
