### ISSUE TITLE
Anzeige der Mitarbeiter

### ISSUE THREAD

**Issue by brauna01** [hcrudolph/swe-project#73]
![mitarbeiter](https://cloud.githubusercontent.com/assets/8896573/5606596/554633ee-9436-11e4-8748-07e2ab9b3cd1.jpg)
Die Performance hat Markus wohl soweit recht gut verbessert, denke was bei mir noch etwas gedauert hat lag an meinem langsamen Internet.

JEDOCH ist jetzt dieses Anzeigeproblem da, liegt das an der Anpassung?
Außerdem werden da nicht alle Mitarbeiter angezeigt bei mir?! (z.B. testmitarbeiter fehlt)

**Comment by brauna01** [comment]
hoffe ich habe da jetzt nichts doppelt (@bortim)

**Comment by bortim** [comment]
Das Problem liegt daran, dass das glophycon kleiner ist, als das img.
Sobald die Elemente gleich groß sind, ist dieses 'Verziehen' wieder weg.

**Comment by bortim** [comment]
a655608c69e886682770894e8e5aca2eeefe1764
46773bf91491963a3aa4bc64104e9977853b98ca
