### ISSUE TITLE
[CertificatesController] Zertifikate können nicht erstellt werden

### ISSUE THREAD

**Issue by rodichsv** [hcrudolph/swe-project#74]
Aktuell können keine Zertifikate erstellt werden über : 
Studiomanagement -> Zertifikate -> hinzufügen (JSON.parse Error)
Usermanagement -> Zertifikate -> hinzufügen (Diese Aktion kann nur durch eine Ajax-Anfrage ausgelöst werden)

**Comment by bortim** [comment]
Ich bin der Meinung, dass wir das nicht implementieren brauchen.
In der Aufgabenbeschreibung ist es ohnehin nicht beschrieben.
In den bestehenden Interfaces ist es auch nicht vorgesehen beispielsweise einem User ein Zertifikat zuzuordnen (und nur im Usermanagement genügt es nicht).
Hierfür eine Beschreibung über die Datenbank (Admin) in die Dokumentation sollte genügen.
@hcrudolph: Segnest du das so ab?

**Comment by brauna01** [comment]
habe mal das design unterm usermanagement soweit angepasst.
Die Funktionalität hätte ich jetzt noch versucht ebenso wie die anderen hinzubekommen?
Lasse ich dann wohl nun erstmal?

**Comment by bortim** [comment]
Also wenn du das ganze Paket umsetzen kannst, dann stehe ich dir da nicht im Weg :)
Also: Zertifikat erstellen, Zertifikat zuordnen, Zertifikat löschen, Zertifikat 'abordnen'

**Comment by brauna01** [comment]
Ne dann lassen wir es besser :/ ... Erstellen und Löschen dürfte ich noch hin bekommen, der Rest denke ich wird da schon schwieriger :(

**Comment by bortim** [comment]
Okay. Dann mach du den add und delete in den Controllern + GUI.

**Comment by hcrudolph** [comment]
Ähnlich wie #70 Zertifikate sind ein nettes Extra.. `add` und `delete` reicht an der Stelle erstmal

**Comment by bortim** [comment]
Wir haben entschieden dies per Beschreibung direkt in der Datenbank machen zu lassen.
Es ist nicht explizit gefordert, unser System kann eh schon eine große Menge und noch viel mehr.
Dies überlassen wir einem möglichen Folgesemester.
