### ISSUE TITLE
Admin kann keine Accounts ohne deren PW ändern

### ISSUE THREAD

**Issue by brauna01** [hcrudolph/swe-project#75]
Da bei Account-Änderungen die Felder "Passwort" und "Passwort wiederholen" abgeglichen werden, jedoch nur "Passwort" mit dem vorhandenen Passwort gefüllt ist, kommt es hier zur Fehlermeldung 
"Passwort wiederholen
Die Passwörter stimmen nicht überein."

**Comment by bortim** [comment]
dieses verhalten ist doch soweit richtig: Bei der Passwortänderung müssen password und passwordRepeat gleich sein.
Trage ich nur bei password etwas ein, so ist die Bedingung, dass beide gleich sein müssen falsch.
Dieses Verhalten würde ja soweit stimmen.
Wenn das so nicht zutrifft, dann bitte nochmal genauer die Problematik erklären

**Comment by brauna01** [comment]
Ja, das Problem ist aber, wenn man nun z.b. nur die Adresse ändert, kommt die selbe Fehlermeldung.
Gibt zwar die Möglichkeit einfach die Sterne/Punke aus dem Feld "Passwort" zu löschen, dann klappt die Änderung ohne Probleme, aber muss das Feld denn vorausgefüllt sein? :)

**Comment by bortim** [comment]
Das feld ist - zumindest bei mir - nicht vorausgefüllt.
![Keine Vorbeledung des Passworts](https://cloud.githubusercontent.com/assets/9103848/5613405/1cbfd986-94e4-11e4-99ff-b4bd479a7d37.PNG)
![Keine Value beim Editieren](https://cloud.githubusercontent.com/assets/9103848/5613436/736ddeb8-94e4-11e4-9b26-634e03e02848.PNG)

**Comment by brauna01** [comment]
Okay. Bei Chrome ist es bei mir auch leer. Bei Firefox gefüllt!?

**Comment by bortim** [comment]
Vielleicht wird im FireFox der Placeholder übersendet.
Kannst du vielleicht die Serverrequest (öffnen -> get+ speichern -> post) im Browser aufzeichnen und hier hochladen?
Dann könnte ich sehen, was der Server hin und her sendet.

**Comment by brauna01** [comment]
Fehler bei mir im Browser - closed
