### ISSUE TITLE
für die Rolle "Mitglied" werden viele unbenötigte Buttons angezeigt

### ISSUE THREAD

**Issue by tkoberom** [hcrudolph/swe-project#76]
Werden diese Buttons noch entfernt oder bleiben diese ohne Funktion bestehen?

die betroffenen Buttons:
-News: Löschen und Bearbeiten
-Usermanagement-> Zertifikate Hinzufügen ,Löschen und Bearbeiten
-Usermanagement->Allgemein Hinzufügen und Löschen

**Comment by bortim** [comment]
Bitte direkt an Sven geben

**Comment by rodichsv** [comment]
Ich kann über die Permissions nicht die Buttons entfernen, ich kann nur hinterlegen die Funktionen nicht ausführbar sind. 
Bitte mal Stephan fragen, ich glaub er hat für News auch das "Hinzufügen"-Field verschwinden lassen, für Nutzer die nicht eingeloggt sind.

**Comment by bortim** [comment]
Doch das geht relativ einfach.
Einfach in der View eine 'if' drum rum.
Und da die Bedingung rein.
```php
<?php
if(isset($user)) {
    if($user['role'] > 0) {
        echo '<button></button>';
    }
}
?>
```

**Comment by rodichsv** [comment]
Ich habe aktuell, das Problem das ich nicht ganz sehe, wie der Edit- und Delete-Button bei Posts geladen wird. 
Für die anderen Buttons (wie z.B. Hinzufügen bei Kursen) wird ein Extra-Button geladen, diese habe ich bereits anhand der Rolle ausgeblendet. 
Hat jemand einen Tip für mich wo genau bei posts die Buttons erstellt werden?
Vielen Dank im Voraus. :)

**Comment by rodichsv** [comment]
Hallo Markus,
warum sollten Trainer die Zertifikate ändern/löschen dürfen? 
(Der böswillige Trainer könnte andere Trainer-Zertifikate entfernen)
Meiner Meinung nach sollte das nur der Admin dürfen?

**Comment by bortim** [comment]
Kannst du machen. Ich habe das nicht so detailreich im Kopf ;)

**Comment by bortim** [comment]
Ist das Thema nun abgehakt?

**Comment by rodichsv** [comment]
Wir können das Issue schließen. :)
