### ISSUE TITLE
Certificate Design muss angepasst werden

### ISSUE THREAD

**Issue by tkoberom** [hcrudolph/swe-project#77]
EditCertificate sowie die normale Certificate-Page müssen noch aufgehübscht werden.

-Größe und Anordnung der einzelnen Zertifikate
-Positionierung bei EditCertificate

**Comment by bortim** [comment]
Diese Funktionen sind derzeit nicht priorisiert und stehen eher vor dem Rückbau.

**Comment by tkoberom** [comment]
Meinst du jetzt die Zertifikate in Usermanagement oder Studiomanagement? Ich habe mich auf das Usermanagement bezogen und würde die Zertifikate vllt so darstellen wie die Kurse und User in Studiomanagement.

**Comment by bortim** [comment]
Im Usermanagement benötigt man aber keine Zertifikate, da man hier ohnehin nur seinen eigenen Account sieht.
Diese werden vom Druckereisystem geliefert.
> Rechnungen, Teilnehmerzertifikate und sämtlicher Briefverkehr werden über ein Druckereisystem abgewickelt

**Comment by tkoberom** [comment]
Alles klar

**Comment by bortim** [comment]
Deswegen kann Zertifikate vollständig abgemanaged werden.

**Comment by JannikZed** [comment]
warte warte, meinst ud Trainer Zertifikate? Die Popover auf der Trainerseite sehen gut aus und sollten bleiben. Dann nenn es halt nicht Zertifikat sondern Trainerinfo. Da kann der Trainer einen Satz zu sich selber schreiben oder so. Kann man ja manuell über phpmyadmin reinschreiben und ende

**Comment by bortim** [comment]
Jein. Grundsätzlich sind trainerzertifikate dasselbe wie die userzertifikate. Wir werden keine gui bauen diese einzufugen.
Wir werden aber eine Beschreibung machen, damit für Trainer das angegeben werden kann.
Das ist für mich/uns der einfachste Weg. Die Aufgabenstellung ist ja bereits erfüllt.

**Comment by JannikZed** [comment]
ja sag ich ja, lass das Feature drin. Insbesondere das Popover bei Trainer sieht sehr gut aus.

**Comment by bortim** [comment]
Das bleibt schon :+1:
