### ISSUE TITLE
Thumbnailhöhe in kurse

### ISSUE THREAD

**Issue by jmpy-** [hcrudolph/swe-project#78]
how to fix glyphicon = rest der thumbnails?!?!? -____-

**Comment by brauna01** [comment]
Etwas genauer? :x

**Comment by jmpy-** [comment]
Jannik hat die Images jetzt gefixed, Issue besteht weiterhin, wenn man auf eine nicht bestehende ID verweist, dann erscheint das Glyphicon, ist allerdings nicht gleich hoch wie die anderen thumbnails, sondern höher/quadratisch, kannst du lokal testen, indem du für einen bestimmten Kurs das Bild rausnimmst

**Comment by bortim** [comment]
Das liegt daran, dass die Glyphicons lediglich quadratisch Skalieren.
Wenn du die Anzeigebilder quadratisch machst (style="height:100px;"), dann passt's wieder.

**Comment by jmpy-** [comment]
Ist in Kurse schon mit style="height:150px;" implementiert, genau nach dem Vorbild bei Mitarbeiter, ging trotzdem nicht
