### ISSUE TITLE
[Unser Studio] Startseite

### ISSUE THREAD

**Issue by jmpy-** [hcrudolph/swe-project#79]
Hey, hab nach bestem Wissen und Gewissen die Studioinfo-Seite als Startseite der Sidebar etc. versucht einzubinden (vgl.: 783c25bdf8f3b3488ceb5b98827657984d2f9882), klappt aber noch nicht so, wie es soll.
Es wird weiterhin die Posts reingeladen, auch wenn immerhin in der Sidebar Studio aktiv wird^^

**Comment by bortim** [comment]
Ich denke, dass es an dem redirect liegt.
Deswegen gebe ich es an @hcrudolph weiter.

**Comment by hcrudolph** [comment]
hiermit behoben: 4ebff8ef64ddda28bd224ec8e315f6182961a5ff
