### ISSUE TITLE
Content verschiebt sich beim zoomen nach links oder rechts

### ISSUE THREAD

**Issue by tkoberom** [hcrudolph/swe-project#81]
Ich habe gerade die Gesamtposition ein wenig zentriert. Dannach habe ich nochmal getestet und der Content hat sich verschoben. 
Hat jemand eine Idee woran das liegen könnte? Durch Verändern von % oder px-Einheiten hat sich nichts geändert.

**Comment by bortim** [comment]
Kannst du vielleicht einen Screenshot hochladen?
Grundsätzlich würde ich sagen: das meiste zeit ist absolut positioniert -> von links oben aus die Pixel zählen.

**Comment by bortim** [comment]
Du müsstest eigentlich nur im application.css bei der Beschreibung von 'content' den left-wert ändern.
Sieht für mich so aus, als hättest du einfach bei allen sachen ein bisschen mehr beim left hinzugefügt.
der einfachste weg ist folgender:
Der einfachere Weg das alles zu zentrieren wäre wohl über eine Grid zu gehen.
dazu muss man aber ggf. auch die postion:absolut wegmachen.
Müsste man mal schauen, wie sich das auf mobilen Geräten (viewport und so) verhält.
Aber ihr seit im Frontend die Profis.

**Comment by bortim** [comment]
Warum macht ihr das nicht einfach rückgängig - alles.
Ihr unterschätzt unterschiedliche Auflösungen und Displaygrößen.
Davor hat es auf Handys automatisch auf das ganze Display skaliert, im Browser genügt der zoom (Strg + +/Strg + -).
Ich verstehe auch nicht, warum ihr das Live-System in diesem halbgaren Zustand hinterlässt.

Schöne Grüße

**Comment by tkoberom** [comment]
Es lag am der #container-ID, diese musste auch mit einem "left" versehen werden.

**Comment by bortim** [comment]
Gewünschtes Verhalten wurde mit [fb7d1960aee4dad28e9af7c49f2f6b1c78384a65] implementiert.
Setzt voraus, dass der Client einen mobile-device-tag sendet.
