### ISSUE TITLE
[StudioController] Tarife

### ISSUE THREAD

**Issue by bortim** [hcrudolph/swe-project#82]
Derzeit gibt es keine Funktion Tarife (für Kursbezahlung) zu erstellen, zu bearbeiten und zu löschen.

**Comment by rodichsv** [comment]
Es lassen sich über Studiomanagement keine Tarife bearbeiten und hinzufügen.
Genutzter Login: testadmin 
Fehlermeldung:
- Hinzufügen: "Der Tarif konnte nicht erstellt werden" (Beschreibung: "Test", Betrag: 10)
- Bearbeiten: Nach mehrmaligen drücken "Sie dürfen die Aktion nicht ausführen", sonst nichts.

----
Daraus resultiert vermutlich ein Fehler beim Hinzufügen von Kursen, dass man kein Tarifmodell auswählen kann.
Fehlermeldung: "Der Kurs benötigt ein Tarifmodell für den Trainer." (siehe Model: Course, validation tariff_id)
Ebenfalls beim Bearbeiten vom Terminplaner ist es nicht möglich Serien-Termine hinzuzufügen.

Einzelne Termine lassen sich hinzufügen.

**Comment by bortim** [comment]
Berichtigt mit:

6ad3bf7954ac80110d6331b35bc0c48bf67d5137

1479de2bf1d572b6256dd4a1e4b45dd8c57a67ce

a6a6c4d6050197492cab802d01bddfb7f14a3efb

 

 

Was noch fehlt: Im Model müssten wir von Kommazahlen (9,99 -> 9.99) 

Das muss noch über ‚beforValidate‘ gemacht werden.

Ebenso muss noch ‚afterFind‘ von . nach Komma geschrieben werden.

@rodichsv: Bitte die beiden Sachen im Tariffs-Model bearbeiten. Vorlagen dazu im DatesController

**Comment by rodichsv** [comment]
Was noch fehlt: Im Model müssten wir von Kommazahlen (9,99 -> 9.99)
-> hängt das mit dem Problem zusammen, warum sich bei Kurs keine Tarife ändern lassen?

**Comment by bortim** [comment]
Das würde ich verneinen.

Das liegt ein einer verhunzten Ausgabe.

Gefixt mit:

c9f2f2560cca5dfc5a88a0344dfccfc8cb4e0423

fa35e527de79fb57b339535fc74a661b4f266c7a

**Comment by bortim** [comment]
@rodichsv, wie sieht es mit den "Umformungen" aus?
Bekommst du das hin?

**Comment by rodichsv** [comment]
den Ansatz wollte ich über eine RegEx lösen.

  public function afterFind($results, $primary = false) {
        foreach ($results as $key => $val) {
            if (isset($val['Tariff']['amount'])) {
                $results[$key]['Tariff']['amount'] = $this->NumberFormatAfterFind($val['Tariff']['amount']);
            }
        }
        return $results;
    }

    public function beforeValidate($options = array())
    {
        if (!empty($this->data['Tariff']['amount'])) {
            $this->data['Tariff']['amount'] = $this->NumberFormatBeforeSave($this->data['Tariff']['amount']);
        }

        return true;
    }

    /**
     * NumberFormatAfterFind()
     *
     * @return $NumberString
     */

    public function NumberFormatAfterFind($NumberString) {
        $string = $NumberString;
        $pattern = '/(\d+),(\d+)/';
        $replacement = '$1.$2';
        $NumberString = preg_replace($pattern, $replacement, $string);
        return ($NumberString);
    }

    public function NumberFormatBeforeSave($NumberString) {
        $string = $NumberString;
        $pattern = '/(\d+).(\d+)/';
        $replacement = '$1,$2';
        $NumberString = preg_replace($pattern, $replacement, $string);
        return ($NumberString);
    }

Allerdings schneidet er trotzdem die letzten Zahlen ab.

**Comment by rodichsv** [comment]
Bitte noch einen Blick drauf werfen, sollte aber so passen.

**Comment by bortim** [comment]
Ich habe noch ein paar kleine Bugfixes vorgenommen:

a0b32b3de309d6bb986404b851c427fb3094c59d

c68b053093e53ebae33ebdcaa7abcc9dc6f56be0

570b482ec6f2613fa3b29f5a56b62695eff61177

0166aa28e05b693f51b7946adf299a91512a4cfc

**Comment by bortim** [comment]
Da soweit alles funktioniert: Close :+1:
