### ISSUE TITLE
Header Design

### ISSUE THREAD

**Issue by JannikZed** [hcrudolph/swe-project#83]
Ich finde auf unserer Seite fehlt derzeit noch ein Header. Ich finde diese Öffnungszeiten und den News Slider ziemlich hässlich. Also wieso nehmen wir nicht den Info Block von "Unser Studio" als header und schreiben die Öffnungszeiten unter "info". Den News slider kann man doch einfach unter "News" machen. Man könnte es doch sicher so machen, dass nur für angemeldete Mitarbeiter alle News zum bearbeiten angezeigt wird, ansonsten nur den News-Slider.
Nur ein Vorschlag von mir, damit die Seite etwas freundlicher und bunter aussieht. Wenn es zuviel Arbeit ist, dann halt nicht :)

**Comment by bortim** [comment]
Solch große Änderungen sind zumindest für mich nicht mehr tragbar.
Wenn es jemand anderes macht, dann ist es mir relativ egal.
Bedenkt aber, dass die Doku schon Sachen beschrieben hat.

**Comment by bortim** [comment]
Da sich hier jetzt nichts mehr tut: Close
