### ISSUE TITLE
[CertificatesController][edit] Alte Fehler werden nicht entfernt

### ISSUE THREAD

**Issue by bortim** [hcrudolph/swe-project#84]
Bei der edit-Aktion werden die alten Fehler nicht entfernt.
Hier muss das JavaScript angepasst werden.

**Comment by brauna01** [comment]
Kann mit "alten Fehler[n]" hier leider nichts anfangen :(

**Comment by bortim** [comment]
Die Fehlerausgabe wird ja wieder mit einer Rotfärbung + Fehlertext ausgegeben.
Wenn ich den Fehler beseitige, aber wo anders einen mache, so bleibt der alte trotzdem rot.

**Comment by bortim** [comment]
Behoben mit: 
ef15885272276da4365cdbcf14f880cbed4371fe

Schönheitskorrektur: 5e210eb690a27e7fc935f77962e22523b4d4c579
