### ISSUE TITLE
Kurs anlegen

### ISSUE THREAD

**Issue by brauna01** [hcrudolph/swe-project#86]
sieht echt gut aus alles inzwischen!
nur bin ich gerade über den Fehler gestolpert, dass ich keinen Kurs anlegen kann.
Anbei mal die Analyse falls da jemand was mit anfangen kann.
![kurs-anlegen](https://cloud.githubusercontent.com/assets/8896573/5654358/8228e486-96c2-11e4-9abb-890462cbccca.jpg)

**Comment by brauna01** [comment]
Die Fehler bei den Feldern (Kursname darf nicht leer sein usw... ) sind nicht der gemeinte Fehler.
Diese stammen noch vom Klick auf Speichern bevor ich was gemacht hatte.

**Comment by bortim** [comment]
Da es ein 500er interner Serverfehler ist, müsste die Antwort vom Server sehen.
Da sind meistens gute Anhaltspunkte drin.
Ist das bei dir lokal am Server oder online?

**Comment by brauna01** [comment]
Online aufgetreten

**Comment by hcrudolph** [comment]
Sollte hiermit behoben sein: cfc724324ffd05e4929bc14f982bbcf10e907b25
Bitte validieren.

**Comment by brauna01** [comment]
Klappt nun wunderbar
