### ISSUE TITLE
[UserController] Mitarbeiter können Mitglieder löschen

### ISSUE THREAD

**Issue by rodichsv** [hcrudolph/swe-project#87]
Wollen wir das so implementieren, dass die Mitarbeiter Mitglieder löschen können?
Aktuell habe ich das eher restriktiv eingerichtet, d.h. Mitarbeiter darf anlegen aber nicht löschen.
(Leider habe ich das auch nicht hinbekommen, die Regel wie oben zu realisieren.)
Was sagt ihr dazu? Das Doku-Team brauch auch eine genaue Aussage dazu.

**Comment by brauna01** [comment]
Es war ja mal aucz möglich, dass Mitglieder  sich selbst löschen können. 
Somit sollten ja eigentlich  auch Mitarbeiter die Mitglieder löschen dürfen. 
Sollte das aber (jetzt noch) zu schwierig  zu implementieren  sein, würde ich es aber lassen.

**Comment by bortim** [comment]
Nach derzeitigem Konzept ist jeder Registrierte Account mit dem grundbetrag bestückt.
Wenn wir niemand löschen können, so muss dieser für immer zahlen.
________________________________
Von: rodichsv<mailto:notifications@github.com>
Gesendet: ‎08.‎01.‎2015 13:34
An: hcrudolph/swe-project<mailto:swe-project@noreply.github.com>
Betreff: [swe-project] [UserController] Mitarbeiter können Mitglieder löschen (#87)

Wollen wir das so implementieren, dass die Mitarbeiter Mitglieder löschen können?
Aktuell habe ich das eher restriktiv eingerichtet, d.h. Mitarbeiter darf anlegen aber nicht löschen.
(Leider habe ich das auch nicht hinbekommen, die Regel wie oben zu realisieren.)
Was sagt ihr dazu? Das Doku-Team brauch auch eine genaue Aussage dazu.

---
Reply to this email directly or view it on GitHub:
https://github.com/hcrudolph/swe-project/issues/87

**Comment by rodichsv** [comment]
Der Admin kann User löschen, jedoch nicht der Trainer.

**Comment by bortim** [comment]
Ah. darauf willst du raus. Also ich habe eigentlich kein Problem damit.
Die Anforderung sagt ja, dass Mitarbeiter die Mitglieder verwalten sollen.

**Comment by rodichsv** [comment]
Naja der Admin ist ja grundsätzlich auch ein Mitarbeiter. ;-)
Wie gesagt, ich habe bisher nicht realisieren können, dass der Mitarbeiter explizit nur Mitglieder löschen kann. Vielleicht seh ich den Wald vor lauter Bäumen nicht. ;-)
Vielleicht kann da noch jemand anderes einen Blick drauf werfen.

**Comment by bortim** [comment]
Man müsste den Datensatz laden:
```php
$deleteUser = $this->Account->find('first', array(
    'conditions'=> array('Account.id' => $id),
    'fields'=>array('Account.role')
));
```
Jetzt müsste man schauen, wie das Array von deleteUser aufgebaut ist..
entweder $deleteUser['Account']['id'] oder $deleteUser['id']
Müsstest du lokal mal austesten.
Darauf aufbauend dann am besten die richtige Bedingung einbauen

**Comment by brauna01** [comment]
27b996b54f340219057d6a2f2f77c30f36d57bce
Hab Freitag Abends nix besseres zu tun :(

**Comment by rodichsv** [comment]
Riesendank an Alex, er hat das hingekriegt !!!
