### ISSUE TITLE
[UserController] [edit] Bearbeiten von Accounts

### ISSUE THREAD

**Issue by rodichsv** [hcrudolph/swe-project#88]
Beim Bearbeiten von Testmitglied durch Testmitarbeiter ist es zwingend erforderlich ein Passwort einzugeben ansonsten wir ein JSON-Error ausgegeben.
Ist das so gewollt?

**Comment by bortim** [comment]
Das Problem hatte Alexander auch schon.
Nach einer Analyse kam heraus, dass er beim Login das Passwort gespeichert hatte.
Kannst du das bitte checken?

**Comment by brauna01** [comment]
Nein. 
Mein Problem war mit nem Admin.
Der Mitarbeiter bekommt wirklich einen Error

**Comment by bortim** [comment]
Undefined index: password APP/Model/Account.php, line 148
Das liegt an folgender Bedingung:
```php
            if ($id != $this->Auth->user('id') && $this->Auth->user('role') == 1) {
                if(empty($this->request->data['Account']['password']))
                    unset($this->request->data['Account']['password']);
                if(isset($this->request->data['Account']['role']))
                    unset($this->request->data['Account']['role']);
            }
```
Hier wird nur das password rausgefiltert. Wenn du das 'passwordRepeat' auch unsettest, sollte es wieder klappen.

Hab bisschen was geändert.
Bitte mal mit allen Accounts testen.

**Comment by brauna01** [comment]
Getestet: (Test)mitarbeiter kann (Test)mitglied ohne Passwort bearbeiten.

**Comment by bortim** [comment]
Dann würde ich hier mal dicht machen.
