### ISSUE TITLE
[Layout] Impressum

### ISSUE THREAD

**Issue by bortim** [hcrudolph/swe-project#90]
Das impressum war ursprünglich im Footer vorgesehen. Meistens haben wir aber unter der Sidebar eine Menge platz. Deswegen ist es sinnvoll an dieser Stelle das impressum zu implementieren.

**Comment by brauna01** [comment]
Sollte hiermit erledigt sein :)
fafcb0445a4ba71ffb347d35556c563eb2fc3cf6

**Comment by bortim** [comment]
Sieht gut aus. :+1:
