### ISSUE TITLE
Öffnungszeiten / Impressum

### ISSUE THREAD

**Issue by brauna01** [hcrudolph/swe-project#91]
Änderungswünsche?
Soll da noch was verändert werden?

Style-technisch aber auch auf den Inhalt bezogen.

**Comment by bortim** [comment]
Die Öffnungszeiten sind leider nicht mehr granular darstellbar.
Gibt es hier die möglichkeit nen hover/click-effekt zu machen? Und das dann nach unten in die seite ausfahren?
