### ISSUE TITLE
Preise ohne Login

### ISSUE THREAD

**Issue by brauna01** [hcrudolph/swe-project#92]
Derzeit bekommt man die Meldung, dass man die Aktion  nicht ausführen  darf wenn man als nicht eingeloggter User auf den Tab "Preise" klickt. Dennoch wird dieser angezeigt.

Ist das so gewollt?

**Comment by bortim** [comment]
@rodichsv: Das ist dein Aufgabengebiet.

**Comment by rodichsv** [comment]
Ich denke es ist sinnvoll, das man den monatlichen Preis sieht wenn man nicht eingeloggt ist. ;)
done
