### ISSUE TITLE
[Model] Keine Validierung von Fremdschlüsseln

### ISSUE THREAD

**Issue by bortim** [hcrudolph/swe-project#95]
Wir haben derzeit keine Validierung von Fremdschlüsseln.
Dies ist - solange man keine böswilligen Absichten hat - kein Problem.
Sendet man aber manuell/manipuliert Daten, so brechen wir mit 'Internal Server Error' ab.

Das System bekommt keinen inkonsistenten Zustand.
Es ist lediglich unschön.

**Comment by rodichsv** [comment]
/*
        'course_id' => array(
                'exists' => array('model'=>'Course', 'field'=>'id',
                'message' => 'Invalid course ID'
                )

        ),
        */
Ist ein Ansatz den ich gefunden habe, funktioniert leider noch nicht da ich diese Abfrage "negieren" müsste, muss wahrscheinlich dann in eine seperate funktion.

**Comment by bortim** [comment]
Eine Möglichkeit wäre, dass du eine Funktion machst.

Diese müsste dann nur auf das betroffene Model eine exists-Abfrage machen.

Dabei hilft dir folgendes: http://book.cakephp.org/2.0/en/models/data-validation.html#adding-your-own-validation-methods

Des Weiteren könnte dir folgender Link noch helfen: https://gist.github.com/iamFIREcracker/1307191

Folgender Link könnte aber die bessere Wahl sein: https://www.bountysource.com/issues/1026037-suggestion-for-validating-foreign-keys

**Comment by rodichsv** [comment]
Erster Test mit course_id war erfolgreich, hab den Umkehrschluss getestet und bei der Abfrage wenn der Kurs existiert mir den Fehler anzuzeigen.

**Comment by bortim** [comment]
Wenn es funktioniert, dann darfst du es gerne schließen :+1:

**Comment by bortim** [comment]
@rodichsv 
Leider sind deine Regeln für die Abfrage von Fremdschlüsseln nicht korrekt.

**Comment by rodichsv** [comment]
Bitte etwas näher spezifizieren, was funktioniert nicht und wie hast du das getestet?

**Comment by bortim** [comment]
Dazu gibt’s später einen Push.

Mir ging es darum:

maxcount auf 2

2 Leute anmelden

maxount auf 1 updaten.

Das sollte unser System ablehnen. Wird aber auch gleich kommen

**Comment by rodichsv** [comment]
Ich habe ja exists()-Prüfungen gemacht, daraufhin baut die Validierung auf, ob dort Werte überhaupt hinterlegt sind. Das wird wiederum auch abgelehnt. 
Den Use-Case, den beschreibst müsste dann noch beinhalten, dass vorher alle Kurse abgesagt werden müssen mit maxcount 2 und neu angelegt werden müssten damit dieser Fall eintreten kann.

Okay, danke und ich bin gespannt. ;)

**Comment by bortim** [comment]
8f5dcb307d73c6efbdcfbedc67d231ea236985c7
6a1b01439e73a5b4ef77ed524e0d8b1c9c2df2f9
1668f2dd76d5f14b8c92b464b48c25a2757d24b5

Bitte Funktionalität nochmals prüfen und abhaken @rodichsv 
- [ ] [CoursesController] Falsche tariff_id
- [ ] [DatesController] Falsche course_id
- [ ] [DatesController] Falsche room_id
- [ ] [DatesController] Falsche director

Zur Überprüfung am besten die 'value' der '<option>' auf einen unsinnig großen Wert setzen und abschicken. Danach einen 'passenden' Eintrag auswählen.

**Comment by rodichsv** [comment]
Aktuell ist es nicht möglich Dates hinzufügen.
--> JSON.parse : unexpected character at line 1 column 1

**Comment by bortim** [comment]
Das lag an einer anderen Sache und wurde direkt mit einem anderen Bug gefixt 😊

Bitte nochmal testen und dementsprechend abhaken.

**Comment by rodichsv** [comment]
Konnte bei den genannten Sachen keine Probleme feststellen. Alle Validierungen funktionieren und werfen eine geeignete Fehlermeldung aus.
Tariff-id lässt sich nicht ändern. Bei aktuellen Kursen sowie bei neuen Kursen wird immer der JkE-Tarif genommen.

**Comment by bortim** [comment]
Für die Tarife gibt es noch ein anderes Issue.
Ich mache dann hier mal dicht. :+1:
