### ISSUE TITLE
Kursmanagement - Icons (An-/Abmelden)

### ISSUE THREAD

**Issue by brauna01** [hcrudolph/swe-project#96]
Hier mal dargestellt wie es bei den unterschiedlichen Rollen ist.
Den Vorschlag habe ich schonmal gepusht (c581257d96a930672cfa089bbeedc06496eafe2b) und würde ich auch lassen wenn es i.O. ist.

![icons-kursmanagement](https://cloud.githubusercontent.com/assets/8896573/5689860/2f579dc0-986f-11e4-9b36-187abd7ecd2c.jpg)

**Comment by brauna01** [comment]
Vorschläge für andere Icons können natürlich auch gemacht werden.
Hier die Auswahl von Bootstrap: http://getbootstrap.com/components/

**Comment by bortim** [comment]
Vielleicht bietet sich auch das glyphicon-check und glyphicon-log-out an.

**Comment by brauna01** [comment]
stimmt. gefallen mir auch besser.
Ist denke ich auch intuitiver. 
Closed dann?

**Comment by bortim** [comment]
Würde ich vorschlagen :1:
