### ISSUE TITLE
Refresh nach Leeren und Befüllen von News-Einträgen

### ISSUE THREAD

**Issue by tkoberom** [hcrudolph/swe-project#97]
Wenn keine Einträge in News vorhanden sind, wird eine entsprechende Meldung wiedergegeben. Allerdings steht diese Meldung immernoch da, wenn man einen Eintrag hinzufügt und wenn man zu einem anderen Tab wechselt und wieder zurück ist die Meldung wieder weg.
Kann mir jemand sagen wie ich die Seite refreshe, damit die Meldung sofort verschwindet?

**Comment by bortim** [comment]
Beim Hinzufügen eines neuen Eintrags wird nach erfolgreicher Rückmeldung des Controllers die ./view/postId geladen.

Diese wird dann einfach an den Anfang des des Containers geladen.

View/Post/view Zeile 90

```javascript $('#postEntries').prepend(view); ```

 

Neu geladen wird – wie du schon erkannt hast – beim Tabwechsel in der Tabbar.

 

Einen ganzen Reload wollte ich nicht umsetzen, da der Server ziemlich belastet wird.

 

Ob sich eine Löschung des ‚Keine Einträge‘ lohnt, weiß ich nicht – tritt ja nur bei Posterstellern auf.

 

Wenn du also wirklich einen ganzen relad machen willst, dann kannst du folgendes machen:

View/Post/view.ctp Zeile 89 – 92 löschen.

Stattdessen: 

```javascript

$.get('<?php echo $this->webroot;?>posts/, function( view ) {

$('#content).html(view);

$('.modal').modal('hide');

});

```

Um ehrlich zu sein halte ich aber wenig davon.

Würde eher dem „Null-Eintrag“ eine eindeutige ID geben.

Dann prüfen, ob diese vorhanden ist.

Wenn sie exisitert, dann $(„#id“).replace(view)

Wenn nicht, dann $('#postEntries').prepend(view);

 

Wenn ihr aber an der Stelle interaktivität einbaut, dann müsst ihr diese beim Löschen auch anpassen.

 

Grüße,

Markus

**Comment by tkoberom** [comment]
Danke für die schnelle Antwort. Ich werde das nochmal mit Stephan absprechen und dann heute Abend umsetzen.
BG, Tom

**Comment by tkoberom** [comment]
Jetzt wird der Content, nach erflogreichen Löschen und Hinzufügen eines Eintrags, neu generiert.
Angepasste Funktionen:
function postAddFormAddSubmitEvent()
function postEntryDelete(postId)
