### ISSUE TITLE
[SWE-Project] Serveradresse für die Webanwendung

### ISSUE THREAD

**Issue by rodichsv** [hcrudolph/swe-project#98]
In der Dokumentation ist aktuell als Pfad für die Anwendung http://82.165.45.70/prod/swe-project/ angegeben. 
Dort scheint aktuell nichts hinterlegt zu sein. --> Not Found

Ich würde vorschlagen, dass die /dev/-Umgebung noch erhalten bleibt, falls wir noch was debuggen müssen in den nächsten Tagen.

**Comment by JannikZed** [comment]
Schau nochmal glatze
