### ISSUE TITLE
Max. Teilnehmer überschreiten

### ISSUE THREAD

**Issue by brauna01** [hcrudolph/swe-project#99]
Wenn man versucht sich bei einem vollen Termin anzumelden, steht ja normal ausgebucht dran, wenn man aber als Admin/Mitarbeiter auf "Termin bearbeiten" geht, und dort auf "Teilnehmer" (Bild Punkt 2), dann kann man noch einen Teilnehmer mehr als das Limit anmelden.

![maxteilnehmer](https://cloud.githubusercontent.com/assets/8896573/5696257/c33e4f66-99c8-11e4-80eb-e8e85fccb60d.jpg)

**Comment by bortim** [comment]
Bugfix: 76a7d083a83adfa1802415ebccd3ade6c4811e89

Bitte nochmal testen.

**Comment by brauna01** [comment]
![maxteilnehmer2](https://cloud.githubusercontent.com/assets/8896573/5697068/5dda2e1a-99e6-11e4-8310-eef8ce45f702.jpg)

**Comment by brauna01** [comment]
jetzt ist da was ganz komisches passiert!!! 

![maxteilnehmer3](https://cloud.githubusercontent.com/assets/8896573/5697083/bd5c855e-99e6-11e4-849b-6db7979f4baa.jpg)

**Comment by bortim** [comment]
Ich habe nochmal einen kleinen Bugfix nachgeschoben: [d0ca3c2ef6b840bed9d8be42eec58b280f975c33]
Bitte nochmal testen.

**Comment by bortim** [comment]
Da keine Rückmeldung: Close
